# Generated by Django 5.1.15 on 2026-10-02 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0002_alter_issuenumbering_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='binding',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='版本'),
        ),
        migrations.AddField(
            model_name='item',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='版本'),
        ),
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_volume', models.CharField(blank=True, max_length=20, verbose_name='盘点卷')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='批次名称')),
                ('state', models.CharField(choices=[('open', '盘点中'), ('closed', '已关闭')], default='open', max_length=10, verbose_name='状态')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktakes', to='serials.title')),
            ],
            options={
                'verbose_name': '盘点批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StocktakeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('item', '实体条码'), ('binding', '装订册条码')], max_length=10, verbose_name='扫描目标类型')),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='目标 id')),
                ('barcode', models.CharField(max_length=60, verbose_name='扫到的条码')),
                ('observed_location', models.CharField(blank=True, max_length=100, verbose_name='扫描架位')),
                ('resolved_item_ids', models.JSONField(default=list, verbose_name='映射实物 ids')),
                ('first_seen_item_ids', models.JSONField(default=list, verbose_name='首次见到实物 ids')),
                ('duplicate', models.BooleanField(default=False, verbose_name='是否重复扫描')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='serials.stocktake')),
            ],
            options={
                'verbose_name': '盘点扫描事件',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StocktakeBindingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_call', models.CharField(max_length=60, verbose_name='装订册索书号')),
                ('location_snapshot', models.CharField(max_length=100, verbose_name='装订位置快照')),
                ('binding_version', models.PositiveIntegerField(verbose_name='装订册版本快照')),
                ('item_ids', models.JSONField(default=list, verbose_name='册内实物 ids')),
                ('binding', models.ForeignKey(blank=True, help_text='装订册可能在盘点期间被拆订删除，故仅置空快照行', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktake_snapshots', to='serials.binding')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binding_snapshots', to='serials.stocktake')),
            ],
            options={
                'verbose_name': '盘点装订快照',
                'unique_together': {('stocktake', 'binding')},
            },
        ),
        migrations.CreateModel(
            name='StocktakeConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('item_changed', '实物被修改（位置/状态）'), ('moved_in', '实物新进入范围'), ('moved_out', '实物离开范围'), ('unbound', '盘点期间被拆订'), ('bound', '盘点期间被装订'), ('rebound', '装订成员重组')], max_length=14, verbose_name='冲突类型')),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('snapshot_value', models.CharField(blank=True, max_length=255, verbose_name='快照值')),
                ('current_value', models.CharField(blank=True, max_length=255, verbose_name='当前值')),
                ('status', models.CharField(choices=[('open', '待处理'), ('resolved', '已解决')], default='open', max_length=10, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktake_conflicts', to='serials.binding')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocktake_conflicts', to='serials.item')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='serials.stocktake')),
            ],
            options={
                'verbose_name': '盘点冲突',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('stocktake', 'item', 'kind'), name='uq_open_conflict_item'), models.UniqueConstraint(condition=models.Q(('item', None), ('status', 'open')), fields=('stocktake', 'binding', 'kind'), name='uq_open_conflict_binding')],
            },
        ),
        migrations.CreateModel(
            name='StocktakeItemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.PositiveBigIntegerField(verbose_name='发行期 id')),
                ('number_ids', models.JSONField(default=list, verbose_name='覆盖期号 ids')),
                ('status_snapshot', models.CharField(max_length=12, verbose_name='盘点开始时状态')),
                ('location_snapshot', models.CharField(blank=True, max_length=100, verbose_name='盘点开始时位置')),
                ('effective_location_snapshot', models.CharField(blank=True, max_length=100, verbose_name='盘点开始时实际位置')),
                ('binding_id_snapshot', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='盘点开始时装订册 id')),
                ('binding_call_snapshot', models.CharField(blank=True, max_length=60, verbose_name='盘点开始时装订册索书号')),
                ('item_version', models.PositiveIntegerField(verbose_name='实物版本快照')),
                ('binding_version', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='装订册版本快照')),
                ('published', models.BooleanField(default=True, verbose_name='已发行')),
                ('result', models.CharField(choices=[('pending', '未见'), ('seen', '已见'), ('misplaced', '错架'), ('review', '待核查'), ('lost', '盘点遗失')], default='pending', max_length=12, verbose_name='盘点结果')),
                ('observed_location', models.CharField(blank=True, max_length=100, verbose_name='扫描架位')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='首次见到时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_snapshots', to='serials.item')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_snapshots', to='serials.stocktake')),
            ],
            options={
                'verbose_name': '盘点实物快照',
                'unique_together': {('stocktake', 'item')},
            },
        ),
    ]
