# Generated by Django 5.1.15 on 2026-10-01 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0002_alter_issuenumbering_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='binding',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='版本号'),
        ),
        migrations.AddField(
            model_name='item',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='版本号'),
        ),
        migrations.CreateModel(
            name='StocktakeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='批次名称')),
                ('status', models.CharField(choices=[('open', '进行中'), ('closed', '已关闭'), ('reopened', '已重新打开')], default='open', max_length=10, verbose_name='批次状态')),
                ('scope_location', models.CharField(blank=True, max_length=100, verbose_name='盘点库位范围')),
                ('completeness_confirmed', models.BooleanField(default=False, verbose_name='范围完整性已确认')),
                ('completed_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认完成时间')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('created_by', models.CharField(blank=True, max_length=60, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktakes', to='serials.title')),
            ],
            options={
                'verbose_name': '盘点批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StocktakeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', '创建批次'), ('scan', '扫描'), ('conflict', '发现冲突'), ('conflict_resolved', '处理冲突'), ('confirmed_complete', '确认范围完成'), ('closed', '关闭批次'), ('loss_confirmed', '确认遗失'), ('reopened', '重新打开')], max_length=20, verbose_name='动作')),
                ('detail', models.CharField(blank=True, max_length=500, verbose_name='说明')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='附加数据')),
                ('actor', models.CharField(blank=True, max_length=60, verbose_name='操作人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='serials.stocktakebatch')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StocktakeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=60, verbose_name='扫描条码')),
                ('scan_kind', models.CharField(choices=[('item', '实体条码'), ('binding', '装订册条码')], default='item', max_length=8, verbose_name='条码类型')),
                ('event_result', models.CharField(choices=[('recorded', '已记录'), ('duplicate', '重复扫描'), ('out_of_scope', '范围外'), ('unknown', '未知条码')], default='recorded', max_length=14, verbose_name='事件结果')),
                ('observed_location', models.CharField(blank=True, max_length=100, verbose_name='扫码时位置')),
                ('resolved_barcodes', models.JSONField(default=list, verbose_name='映射到的实体条码')),
                ('is_duplicate', models.BooleanField(default=False, verbose_name='是否重复')),
                ('scanned_by', models.CharField(blank=True, max_length=60, verbose_name='扫描人')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='serials.stocktakebatch')),
                ('binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_events', to='serials.binding')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repeat_scans', to='serials.stocktakescan')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_events', to='serials.item')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StocktakeScopeNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frozen_holding_status', models.CharField(max_length=20, verbose_name='冻结时馆藏视图')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_numbers', to='serials.stocktakebatch')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_scopes', to='serials.issuenumber')),
            ],
        ),
        migrations.CreateModel(
            name='StocktakeSnapshotBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_number', models.CharField(max_length=60, verbose_name='索书号')),
                ('frozen_location', models.CharField(max_length=100, verbose_name='冻结时位置')),
                ('frozen_version', models.PositiveIntegerField(verbose_name='冻结时版本')),
                ('frozen_item_barcodes', models.JSONField(default=list, verbose_name='冻结时成员条码')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_bindings', to='serials.stocktakebatch')),
                ('binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_binding_rows', to='serials.binding')),
            ],
        ),
        migrations.CreateModel(
            name='StocktakeSnapshotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frozen_status', models.CharField(max_length=12, verbose_name='冻结时状态')),
                ('frozen_location', models.CharField(blank=True, max_length=100, verbose_name='冻结时自身位置')),
                ('frozen_item_version', models.PositiveIntegerField(verbose_name='冻结时实体版本')),
                ('frozen_bound', models.BooleanField(default=False, verbose_name='冻结时是否已装订')),
                ('frozen_binding_call_number', models.CharField(blank=True, max_length=60, verbose_name='冻结时装订索书号')),
                ('frozen_binding_location', models.CharField(blank=True, max_length=100, verbose_name='冻结时实际位置')),
                ('frozen_binding_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='冻结时装订版本')),
                ('result', models.CharField(choices=[('unseen', '未见'), ('seen', '已见'), ('misplaced', '错架'), ('review', '待核查')], default='unseen', max_length=12, verbose_name='盘点结论')),
                ('result_before_review', models.CharField(blank=True, default='', max_length=12, verbose_name='核查前结论')),
                ('observed_location', models.CharField(blank=True, max_length=100, verbose_name='扫到位置')),
                ('baseline', models.CharField(blank=True, default='', help_text='冲突按新状态解决后，基线更新为解决时的结论', max_length=12, verbose_name='当前对照基线')),
                ('baseline_item_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='基线实体版本')),
                ('baseline_bound', models.BooleanField(blank=True, null=True, verbose_name='基线是否装订')),
                ('baseline_binding_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='基线装订版本')),
                ('baseline_location', models.CharField(blank=True, default='', help_text='冲突按现状处理时确认的位置，错架判断以此为准', max_length=100, verbose_name='基线实际位置')),
                ('outcome', models.CharField(choices=[('pending', '待处理'), ('lost_candidate', '遗失候选'), ('lost_confirmed', '已转遗失'), ('kept', '保留')], default='pending', max_length=16, verbose_name='关闭后去向')),
                ('first_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='首次扫到时间')),
                ('baseline_binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_snapshot_rows', to='serials.binding')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_items', to='serials.stocktakebatch')),
                ('frozen_binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_rows', to='serials.binding')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot_rows', to='serials.item')),
            ],
        ),
        migrations.CreateModel(
            name='StocktakeConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('item_moved', '实体被移动或修改'), ('bound', '盘点期间被装订'), ('unbound', '盘点期间被拆订'), ('binding_moved', '装订册被移动'), ('scope_changed', '范围发生变化')], max_length=16, verbose_name='冲突类型')),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('snapshot_value', models.CharField(blank=True, max_length=255, verbose_name='快照值')),
                ('current_value', models.CharField(blank=True, max_length=255, verbose_name='当前值')),
                ('status', models.CharField(choices=[('open', '待处理'), ('resolved_seen', '按现状确认已见'), ('resolved_unseen', '按未见重新核查'), ('resolved_scope', '范围变化已确认')], default='open', max_length=18, verbose_name='处理状态')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('resolved_by', models.CharField(blank=True, max_length=60, verbose_name='处理人')),
                ('resolution_note', models.CharField(blank=True, max_length=255, verbose_name='处理备注')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='serials.stocktakebatch')),
                ('snapshot_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='serials.stocktakesnapshotitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='stocktakebatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'reopened'])), fields=('title',), name='uniq_active_stocktake_per_title'),
        ),
        migrations.AddIndex(
            model_name='stocktakescan',
            index=models.Index(fields=['batch', 'barcode'], name='serials_sto_batch_i_c83f35_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktakescan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_duplicate', False)), fields=('batch', 'barcode'), name='uniq_original_scan_per_batch_barcode'),
        ),
        migrations.AlterUniqueTogether(
            name='stocktakescopenumber',
            unique_together={('batch', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='stocktakesnapshotbinding',
            unique_together={('batch', 'call_number')},
        ),
        migrations.AlterUniqueTogether(
            name='stocktakesnapshotitem',
            unique_together={('batch', 'item')},
        ),
        migrations.AddConstraint(
            model_name='stocktakeconflict',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('snapshot_item', 'kind'), name='uniq_open_conflict_per_row_kind'),
        ),
    ]
